spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teachmgr?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&nullCatalogMeansCurrent = true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456



#spring:
#  datasource:
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #com.mysql.jdbc.Driver 是5版本的驱动
#    #com.mysql。cj.jdbc.Driver 是8版本的驱动
#    #?serverTimezone=UTC 解决时区的报错
#    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&nullCatalogMeansCurrent = true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#server:
#  port: 8000
